import type { Metadata } from 'next';
import { Bricolage_Grotesque } from 'next/font/google';
import './globals.css';
import { NavbarLayout } from '@/components/navbar-layout';

const bricolage = Bricolage_Grotesque({ subsets: ['latin'] });
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body suppressHydrationWarning className={`${bricolage.className}`}>
				<NavbarLayout>{children}</NavbarLayout>
			</body>
		</html>
	);
}
