import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { cn } from '~/libs/utils';
import * as fonts from './fonts';
import './globals.scss';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { Layout } = resources;
	return (
		<html
			lang="en"
			suppressHydrationWarning>
			<body
				suppressHydrationWarning
				className={cn('antialiased', fonts.inter.variable, fonts.bricolage.variable)}>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
const resources = {
	Layout: dynamic(() => import('~/components/layout/app')),
};
