import type { Metadata } from 'next';
import dynamic from 'next/dynamic';
import { cn } from '~/libs/utils';
import * as fonts from './fonts';
import './globals.scss';

const Layout = dynamic(() => import('~/components/layout/app'));
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<script
					src="https://unpkg.com/react-scan/dist/auto.global.js"
					async
				/>
			</head>
			<body className={cn('antialiased', fonts.inter.variable, fonts.bricolage.variable)}>
				<Layout>{children}</Layout>
			</body>
		</html>
	);
}
